// Auto-generated C registry header - DO NOT EDIT DIRECTLY
// Generated by scripts/update_registry.py
#ifndef CREGISTRY_H
#define CREGISTRY_H

#ifdef __cplusplus
extern "C" {
#endif

// Forward declaration for the Context interface
struct Context;
typedef struct Context Context;

// Function pointer type for getting SMILES string
typedef const char* (*GetSmilesFunc)(const void*);

// Helper function that will be provided by the C++ implementation
const char* getSmilesCFunc(const void* ctx);

// Common interface for all C descriptors
// Each descriptor must implement this function to be integrated with the C++ framework

// C implementation of SmilesAdjacentHeteroatomRatio
double calculateSmilesAdjacentHeteroatomRatio(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesAlcoholCount
double calculateSmilesAlcoholCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesAldehydeCount
double calculateSmilesAldehydeCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesAliphaticChainCount
double calculateSmilesAliphaticChainCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesAlkyneCount
double calculateSmilesAlkyneCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesAlternatingElementPattern
double calculateSmilesAlternatingElementPattern(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesAmideCount
double calculateSmilesAmideCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesAmideFraction
double calculateSmilesAmideFraction(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesAmideToNitrogenRatio
double calculateSmilesAmideToNitrogenRatio(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesAnhydrideCount
double calculateSmilesAnhydrideCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesAromaticBondCount
double calculateSmilesAromaticBondCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesAromaticCarbonCount
double calculateSmilesAromaticCarbonCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesAromaticCarbonHeteroatomCount
double calculateSmilesAromaticCarbonHeteroatomCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesAromaticHalogenCount
double calculateSmilesAromaticHalogenCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesAromaticNitrogenCount
double calculateSmilesAromaticNitrogenCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesAromaticOxygenCount
double calculateSmilesAromaticOxygenCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesAromaticRingEdge
double calculateSmilesAromaticRingEdge(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesAromaticSulfurCount
double calculateSmilesAromaticSulfurCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesAtomicEntropy
double calculateSmilesAtomicEntropy(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesAzideCount
double calculateSmilesAzideCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesBenzimidazoleCount
double calculateSmilesBenzimidazoleCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesBenzothiazoleCount
double calculateSmilesBenzothiazoleCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesBenzoxazoleCount
double calculateSmilesBenzoxazoleCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesBenzylCount
double calculateSmilesBenzylCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesBiphenylCount
double calculateSmilesBiphenylCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesBondTypeDiversity
double calculateSmilesBondTypeDiversity(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesBoronCount
double calculateSmilesBoronCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesBracketAtomCount
double calculateSmilesBracketAtomCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesBranchCloseCount
double calculateSmilesBranchCloseCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesBranchOpenCount
double calculateSmilesBranchOpenCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesBranchedAmideCount
double calculateSmilesBranchedAmideCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesBranchingIndex
double calculateSmilesBranchingIndex(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesBromineCount
double calculateSmilesBromineCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesCarbamatCount
double calculateSmilesCarbamatCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesCarbohydrateLikeness
double calculateSmilesCarbohydrateLikeness(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesCarbonAromaticityFraction
double calculateSmilesCarbonAromaticityFraction(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesCarbonCount
double calculateSmilesCarbonCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesCarbonPhosphorusBondCount
double calculateSmilesCarbonPhosphorusBondCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesCarbonylDistribution
double calculateSmilesCarbonylDistribution(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesCarbonylHeteroatomCount
double calculateSmilesCarbonylHeteroatomCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesCarboxylateCount
double calculateSmilesCarboxylateCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesChainLengthDistribution
double calculateSmilesChainLengthDistribution(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesChiralCenterCount
double calculateSmilesChiralCenterCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesChiralCenterDensity
double calculateSmilesChiralCenterDensity(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesChiralityDistribution
double calculateSmilesChiralityDistribution(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesChlorineCount
double calculateSmilesChlorineCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesComplexRingClosureCount
double calculateSmilesComplexRingClosureCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesConjugatedSystemCount
double calculateSmilesConjugatedSystemCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesCyclobutylCount
double calculateSmilesCyclobutylCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesCyclohexylCount
double calculateSmilesCyclohexylCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesCyclopentylCount
double calculateSmilesCyclopentylCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesCyclopropylCount
double calculateSmilesCyclopropylCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesDiazoCount
double calculateSmilesDiazoCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesDimethylCount
double calculateSmilesDimethylCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesDisulfideCount
double calculateSmilesDisulfideCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesDotCount
double calculateSmilesDotCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesDoubleBondCount
double calculateSmilesDoubleBondCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesDoubleBondRingJunctionCount
double calculateSmilesDoubleBondRingJunctionCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesEsterCount
double calculateSmilesEsterCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesEtherCount
double calculateSmilesEtherCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesFluorinatedFragmentCount
double calculateSmilesFluorinatedFragmentCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesFluorineCount
double calculateSmilesFluorineCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesFluorineToCarbonRatio
double calculateSmilesFluorineToCarbonRatio(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesFragmentComplexity
double calculateSmilesFragmentComplexity(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesFuranCount
double calculateSmilesFuranCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesFusedRingCount
double calculateSmilesFusedRingCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesGeneralAmmoniumCount
double calculateSmilesGeneralAmmoniumCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesGuanidineBasicCount
double calculateSmilesGuanidineBasicCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesHalogenCount
double calculateSmilesHalogenCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesHeteroatomClustering
double calculateSmilesHeteroatomClustering(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesHeteroatomSequenceCount
double calculateSmilesHeteroatomSequenceCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesHeterocycleCountNormalized
double calculateSmilesHeterocycleCountNormalized(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesHydrazideCount
double calculateSmilesHydrazideCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesHydrazoneCount
double calculateSmilesHydrazoneCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesHydrophilicGroupDensity
double calculateSmilesHydrophilicGroupDensity(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesImidazoleBasicCount
double calculateSmilesImidazoleBasicCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesImidazoliumCount
double calculateSmilesImidazoliumCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesIndoleCount
double calculateSmilesIndoleCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesIodineCount
double calculateSmilesIodineCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesIonizableAmineCount
double calculateSmilesIonizableAmineCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesIonizableImidazoleCount
double calculateSmilesIonizableImidazoleCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesIonizableNitrogenCount
double calculateSmilesIonizableNitrogenCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesIonizableOxygenCount
double calculateSmilesIonizableOxygenCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesIonizablePhenolCount
double calculateSmilesIonizablePhenolCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesIonizablePhosphorusCount
double calculateSmilesIonizablePhosphorusCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesIonizablePyridineCount
double calculateSmilesIonizablePyridineCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesIonizableSulfonamideCount
double calculateSmilesIonizableSulfonamideCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesIonizableSulfurCount
double calculateSmilesIonizableSulfurCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesIsocyanateCount
double calculateSmilesIsocyanateCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesIsocyanideCount
double calculateSmilesIsocyanideCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesKetoneCount
double calculateSmilesKetoneCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesMethylationDegree
double calculateSmilesMethylationDegree(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesMorpholineCount
double calculateSmilesMorpholineCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesNAlkylCount
double calculateSmilesNAlkylCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesNaphthaleneCount
double calculateSmilesNaphthaleneCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesNegativeChargeCount
double calculateSmilesNegativeChargeCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesNitrileCount
double calculateSmilesNitrileCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesNitroCount
double calculateSmilesNitroCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesNitrogenAromaticityFraction
double calculateSmilesNitrogenAromaticityFraction(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesNitrogenCount
double calculateSmilesNitrogenCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesNitrogenEnvironmentDiversity
double calculateSmilesNitrogenEnvironmentDiversity(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesNitrogenOxidationStateDistribution
double calculateSmilesNitrogenOxidationStateDistribution(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesNitrogenPositionVariance
double calculateSmilesNitrogenPositionVariance(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesNonCarbonBackboneRatio
double calculateSmilesNonCarbonBackboneRatio(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesOximeCount
double calculateSmilesOximeCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesOxygenClusteringFactor
double calculateSmilesOxygenClusteringFactor(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesOxygenCount
double calculateSmilesOxygenCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesPhenolCount
double calculateSmilesPhenolCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesPhenylCount
double calculateSmilesPhenylCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesPhosphateAnionCount
double calculateSmilesPhosphateAnionCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesPhosphateCount
double calculateSmilesPhosphateCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesPhosphorusCount
double calculateSmilesPhosphorusCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesPhosphorusOxidationStateDistribution
double calculateSmilesPhosphorusOxidationStateDistribution(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesPiperazineCount
double calculateSmilesPiperazineCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesPiperidineCount
double calculateSmilesPiperidineCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesPositionWeightedHeteroRatio
double calculateSmilesPositionWeightedHeteroRatio(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesPositiveChargeCount
double calculateSmilesPositiveChargeCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesPrimaryAmineCount
double calculateSmilesPrimaryAmineCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesPrimaryAmineRatio
double calculateSmilesPrimaryAmineRatio(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesPyridineCount
double calculateSmilesPyridineCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesPyridiniumCount
double calculateSmilesPyridiniumCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesPyrimidineCount
double calculateSmilesPyrimidineCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesPyrroleCount
double calculateSmilesPyrroleCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesQuaternaryAmmoniumBasicCount
double calculateSmilesQuaternaryAmmoniumBasicCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesRingBridgeCount
double calculateSmilesRingBridgeCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesRingClosureCount
double calculateSmilesRingClosureCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesRingJunctionDensity
double calculateSmilesRingJunctionDensity(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesSecondaryAmineCount
double calculateSmilesSecondaryAmineCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesSingleBondCount
double calculateSmilesSingleBondCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesSpiroCompoundCount
double calculateSmilesSpiroCompoundCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesStereoBackwardCount
double calculateSmilesStereoBackwardCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesStereoForwardCount
double calculateSmilesStereoForwardCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesStructuralSymmetry
double calculateSmilesStructuralSymmetry(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesSulfonamideCount
double calculateSmilesSulfonamideCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesSulfonateCount
double calculateSmilesSulfonateCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesSulfonicAcidCount
double calculateSmilesSulfonicAcidCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesSulfurCount
double calculateSmilesSulfurCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesSulfurOxidationStateDistribution
double calculateSmilesSulfurOxidationStateDistribution(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesTerminalGroupDiversity
double calculateSmilesTerminalGroupDiversity(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesTertiaryAmineBasicCount
double calculateSmilesTertiaryAmineBasicCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesTertiaryCarbonCount
double calculateSmilesTertiaryCarbonCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesThiocyanateCount
double calculateSmilesThiocyanateCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesThioetherCount
double calculateSmilesThioetherCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesThiolCount
double calculateSmilesThiolCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesThiomorpholineCount
double calculateSmilesThiomorpholineCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesThiopheneCount
double calculateSmilesThiopheneCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesThioureaCount
double calculateSmilesThioureaCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesTrifluoromethylCount
double calculateSmilesTrifluoromethylCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesTrifunctionalCarbonRatio
double calculateSmilesTrifunctionalCarbonRatio(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesTripleBondCount
double calculateSmilesTripleBondCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesUreaCount
double calculateSmilesUreaCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SmilesZwitterionCount
double calculateSmilesZwitterionCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitActivationDensity
double calculateSpitActivationDensity(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitAntiDiagonalAsymmetryScore
double calculateSpitAntiDiagonalAsymmetryScore(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitAverageDistanceWeightedActivation
double calculateSpitAverageDistanceWeightedActivation(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitBandwidthTop10Activation
double calculateSpitBandwidthTop10Activation(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitBondAtomInteractionCount
double calculateSpitBondAtomInteractionCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitBondPairAsymmetry
double calculateSpitBondPairAsymmetry(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitBondVsRingSeparationScore
double calculateSpitBondVsRingSeparationScore(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitCenterOfMatrixActivationShift
double calculateSpitCenterOfMatrixActivationShift(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitCheckerboardPatternStrength
double calculateSpitCheckerboardPatternStrength(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitDiagonalDominanceIndex
double calculateSpitDiagonalDominanceIndex(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitEdgeTokenInteractionBias
double calculateSpitEdgeTokenInteractionBias(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitFeatureCooccurrenceCorrelation
double calculateSpitFeatureCooccurrenceCorrelation(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitFeatureImportanceIndexPCA
double calculateSpitFeatureImportanceIndexPCA(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitFeatureSpecificSparsity
double calculateSpitFeatureSpecificSparsity(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitFeatureWiseEntropy
double calculateSpitFeatureWiseEntropy(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitGridUniformity
double calculateSpitGridUniformity(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitHighestInteractiveToken
double calculateSpitHighestInteractiveToken(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitInterClassInteractionRatio
double calculateSpitInterClassInteractionRatio(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitIntraClassInteractionRatio
double calculateSpitIntraClassInteractionRatio(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitKurtosisBondPairScores
double calculateSpitKurtosisBondPairScores(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitLPatternMotifCount
double calculateSpitLPatternMotifCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitLowerTriangleActivationRatio
double calculateSpitLowerTriangleActivationRatio(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitMatchingTokenPairCount
double calculateSpitMatchingTokenPairCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitMatrixTraceScore
double calculateSpitMatrixTraceScore(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitMax3x3InteractionPatchScore
double calculateSpitMax3x3InteractionPatchScore(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitMaxDiagonalActivity
double calculateSpitMaxDiagonalActivity(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitMeanActivationAcrossRows
double calculateSpitMeanActivationAcrossRows(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitMeanOfFeaturePlanes
double calculateSpitMeanOfFeaturePlanes(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitMeanOffDiagonalSimilarity
double calculateSpitMeanOffDiagonalSimilarity(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitMeanTokenIndexDistance
double calculateSpitMeanTokenIndexDistance(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitMostConnectedTokenScore
double calculateSpitMostConnectedTokenScore(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitMostFrequentInteractionPattern
double calculateSpitMostFrequentInteractionPattern(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitNonZeroCellsPerFeature
double calculateSpitNonZeroCellsPerFeature(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitPositionallyStableTokens
double calculateSpitPositionallyStableTokens(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitRepetitiveTokenMotifCount
double calculateSpitRepetitiveTokenMotifCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitRingParticipationIndexPerToken
double calculateSpitRingParticipationIndexPerToken(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitRingRelatedTokenPairCount
double calculateSpitRingRelatedTokenPairCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitRingSymmetryIndex
double calculateSpitRingSymmetryIndex(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitSelfPairCount
double calculateSpitSelfPairCount(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitSkewnessInteractionMatrix
double calculateSpitSkewnessInteractionMatrix(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitStdDevTokenIndexDistances
double calculateSpitStdDevTokenIndexDistances(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitSymmetryUnder90Rotation
double calculateSpitSymmetryUnder90Rotation(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitTokenClusterEntropy
double calculateSpitTokenClusterEntropy(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitTokenEntropy
double calculateSpitTokenEntropy(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitTokenHighestBondInteractions
double calculateSpitTokenHighestBondInteractions(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitTokenRepeatSpan
double calculateSpitTokenRepeatSpan(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitTokenSymmetryIndex
double calculateSpitTokenSymmetryIndex(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitTokenTransitionEntropy
double calculateSpitTokenTransitionEntropy(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitTopLeftToBottomRightImbalance
double calculateSpitTopLeftToBottomRightImbalance(const void* context, GetSmilesFunc getSmilesFunc);

// C implementation of SpitVarianceOfFeaturePlanes
double calculateSpitVarianceOfFeaturePlanes(const void* context, GetSmilesFunc getSmilesFunc);

#ifdef __cplusplus
}
#endif

#endif // CREGISTRY_H