// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/update_registry.py

#pragma once

namespace desfact {

// Initialize the registry - ensures all static registrations take place
void initializeRegistry();

} // namespace desfact
